# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R2DBC
email: r2dbc@vmware.com
description: > # this means to ignore newlines until "baseurl:"
  R2DBC 0.8.1.RELEASE: A standard API for reactive programming using SQL databases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://r2dbc.github.io" # the base hostname & protocol for your site
twitter_username: r2dbc
github_username:  r2dbc

# Build settings
markdown: kramdown
